apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
  labels:
    app: react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: react
        tier: frontend
    spec:
      containers:
      - image: firoj0786/reactapp
        name: react
        ports:
        - containerPort: 80
          name: react
        
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 20
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        
