apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpareact           
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: react
  minReplicas: 1
  maxReplicas: 4
  # targetCPUUtilizationPercentage: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 100Mi
